[build]
    functions = "functions"
[[redirects]]
  from = "/api/userDoc"
  to = "/.netlify/functions/getUserDoc"
  status = 200
  
[[redirects]]
  from = "/api/userCollection"
  to = "/.netlify/functions/getUserCollection"
  status = 200